version: '3'

services:
  simulator:
    build: .
    tty: true
    hostname: interscity.local
    volumes:
      - '.:/sim-diasca'
    command: bash -c "make all && cd mock-simulators/smart_city_model/src && make all && ls .. && make smart_city_run CMD_LINE_OPT='--batch'"


networks:
  default:
    external:
      name: interscity
