% Header automatically generated by the 'all-pre-hook'
% make target.

-define( common_version, "0.1" ).
-define( wooper_version, "1.0" ).
-define( traces_version, "0.3" ).
-define( sim_diasca_version, "2.2.11-rc1" ).
-define( mock_simulators_version, "0.1" ).
